version: "3.8"

services:
  # MySQL database service
  database:
    build: ./mysql
    container_name: mysql-container
    ports:
      - "3306:3306" # Expose MySQL on localhost:3306
    volumes:
      - todo-data:/var/lib/mysql # To persist database data
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  # Backend system service
  backend:
    build: ./todo-fullstack-backend-mysql
    container_name: todo-backend-container
    ports:
      - "5001:5001" # Expose backend on localhost:5001
    depends_on:
      - database # Wait for the database container to be up before starting backend
    networks:
      - todo-network
    command: ["sh", "-c", "sleep 10 && npm start"] # Wait for the database container to be up before starting backend

  # Frontend system service
  frontend:
    build: ./todo-fullstack-frontend
    container_name: todo-frontend-container
    ports:
      - "3000:3000" # Expose frontend on localhost:3000 (adjust if needed)
    depends_on:
      - backend # Wait for the backend container to be up before starting frontend
    networks:
      - todo-network

# Define a shared network for the services to communicate
networks:
  todo-network:

# Define a volume for the MySQL database data persistence
volumes:
  todo-data:
